# Generated by Django 2.1.4 on 2019-01-03 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_number', models.IntegerField()),
                ('cpu_current_freq', models.DecimalField(decimal_places=10, max_digits=19)),
                ('cpu_min_freq', models.DecimalField(decimal_places=10, max_digits=19)),
                ('cpu_max_freq', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Disk_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_size', models.BigIntegerField()),
                ('size_used', models.BigIntegerField()),
                ('size_free', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('adresse_ip', models.CharField(max_length=50)),
                ('adresse_mac', models.CharField(max_length=50)),
                ('etat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interface_data_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte_send', models.BigIntegerField()),
                ('byte_recv', models.BigIntegerField()),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Moniteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ram_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_total', models.BigIntegerField()),
                ('ram_available', models.BigIntegerField()),
                ('ram_percent', models.BigIntegerField()),
                ('ram_free', models.BigIntegerField()),
                ('ram_used', models.BigIntegerField()),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='moniteur',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Utilisateur'),
        ),
        migrations.AddField(
            model_name='disk_info',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Equipement'),
        ),
        migrations.AddField(
            model_name='cpu_info',
            name='equipement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Equipement'),
        ),
    ]
