# Generated by Django 2.1.4 on 2019-01-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk_info',
            name='size_free',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='disk_info',
            name='size_used',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='disk_info',
            name='total_size',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
