# Generated by Django 2.1.3 on 2019-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
