# Generated by Django 2.1.3 on 2019-01-03 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_equipement_moniteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_number', models.DecimalField(decimal_places=10, max_digits=19)),
                ('cpu_current_freq', models.DecimalField(decimal_places=10, max_digits=19)),
                ('cpu_min_freq', models.DecimalField(decimal_places=10, max_digits=19)),
                ('cpu_max_freq', models.DecimalField(decimal_places=10, max_digits=19)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Disk_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_size', models.BigIntegerField()),
                ('size_used', models.BigIntegerField()),
                ('size_free', models.BigIntegerField()),
                ('equiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Interface_data_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte_send', models.BigIntegerField()),
                ('byte_recv', models.BigIntegerField()),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Ram_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_total', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ram_available', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ram_percent', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ram_free', models.DecimalField(decimal_places=10, max_digits=19)),
                ('ram_used', models.DecimalField(decimal_places=10, max_digits=19)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Equipement')),
            ],
        ),
    ]
