# Generated by Django 2.1.3 on 2019-02-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_auto_20190201_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=20)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.Utilisateur')),
            ],
        ),
        migrations.RemoveField(
            model_name='moniteur',
            name='version',
        ),
    ]
