# Generated by Django 2.1.3 on 2019-01-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_cpu_info_disk_info_interface_data_info_ram_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='adress_ip',
            new_name='adresse_ip',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='adress_mac',
            new_name='adresse_mac',
        ),
    ]
