# Generated by Django 2.1.3 on 2019-01-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20190103_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk_info',
            old_name='equiment',
            new_name='equipement',
        ),
    ]
