# Generated by Django 2.1.3 on 2019-01-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0006_auto_20190103_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_info',
            name='cpu_number',
            field=models.DecimalField(decimal_places=19, max_digits=19),
        ),
        migrations.AlterField(
            model_name='ram_info',
            name='ram_available',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ram_info',
            name='ram_free',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ram_info',
            name='ram_percent',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ram_info',
            name='ram_total',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ram_info',
            name='ram_used',
            field=models.BigIntegerField(),
        ),
    ]
