# Generated by Django 2.1.3 on 2019-01-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0007_auto_20190103_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu_info',
            name='cpu_number',
            field=models.IntegerField(),
        ),
    ]
